### ISSUE TITLE
Instructions on how to run name and condition extraction on generated samples

### ISSUE THREAD

**Issue by Touzen** [elehman16/exposing_patient_data_release#3]
Thank you for your very interesting work and for providing the code so that your experiments are easy to replicate. I am also really grateful for the helpful documentation that you have provided,

However, I can't manage to run the scripts `name_condition_extraction.py` and `name_extraction.py`. The script requires that my environment has the variables `MEDCAT_VOCAB_FILE` and `MEDCAT_CDB_FILE` set (`subject_id_to_medcat_preprocess.py:13` and onward), but I can't figure out where these files are located, or how I should build them.

A clarification regarding this would be incredibly appreciated! Please also let me know if there are other environment variables that need to be set.

**Comment by elehman16** [comment]
I would recommend downloading all of our preprocessed files from `https://physionet.org/content/clinical-bert-mimic-notes/1.0.0/`. If you still want to be able to run MedCAT (for whatever reason), please reach out to this Github [here](https://github.com/CogStack/MedCAT).

**Comment by Touzen** [comment]
Sorry for being a bit unclear in my question. I already have all the preprocessed file, and my intention is not to do any preprocessing. I want to run the script experiments that extract data from the generated sample sentences. As I understand it, the scripts that should be run are `name_condition_extraction.py` and `name_extraction.py`?

Running the first script yields the following output:
```
$ python experiments/generation/name_condition_extraction.py
Traceback (most recent call last):
  File "experiments/generation/name_condition_extraction.py", line 10, in <module>
    from setup_scripts.subject_id_to_medcat_preprocess import get_entities
  File "/data0/home/dsv/thva5058/exposing_patient_data_release/setup_scripts/subject_id_to_medcat_preprocess.py", line 13, in <module>
    vocab.load_dict(os.environ["MEDCAT_VOCAB_FILE"])
  File "/home/dsv/thva5058/anaconda3/envs/exposing/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
```
It seems that these files are needed to run the experiment, since the `get_entities` method uses an object called `cat` which is built from data ultimately relying on the environment variables I mentioned.

**Comment by successar** [comment]
Hi @Touzen , I can send you the medcat files but I need the screenshot of your umls profile first with your name and email (you can redact other information if you want). Please send it to successar@gmail.com . Thanks !
